version: '2'
services:
    musicrecommender:
        build: ../../musicrecommender
        command: /bin/sh -c "cd WebSite; ls -l; python prepareDB.py; echo prep done; python manage.py runserver 0.0.0.0:8000; echo manage done"
        ports:
            - 8000:8000

    redis:
        image: redis
    dynomite:
        image: dictcp/dynomite
        ports:
            - "8101:8101"
            - "8102:8102"
            - "22222:22222"
        depends_on:
            - redis
        links:
            - redis:redisserver
    graphite:
        image: hopsoft/graphite-statsd
    grafana:
        image: grafana/grafana
        ports:
            - "3000:3000"
    #image-service:
    #    image: sius/flask-image-service
